sudo: required
language: node_js
node_js:
  - '10'
services:
  - docker
cache: npm
install: npm install
script:
  - npm run build
  - make image
deploy:
  provider: script
  script: make push
  on:
    branch: master
notifications:
  email: false
